version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ENV['DB_PASSWORD']
      MYSQL_DATABASE: ENV['DB_DATABASE']
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "4306:3306"

  app:
    tty: true
    stdin_open: true
    environment:
      - RAILS_SERVE_STATIC_FILES=true
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build: containers/nginx
    volumes:
    - public-data:/app/public
    - tmp-data:/app/tmp
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: