version: '2'
services:
  web:
    build: .
    volumes:
      - /app/log # persist logs
    depends_on:
      - db

  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: <%= Rails.application.credentials.rds[:password] %>
      MYSQL_DATABASE: <%= Rails.application.credentials.rds[:username] %>